version: '3'

services:

    nginx:    
        image: nginx:1.20.0
        container_name: Stocklist-nginx
        ports:
            - 8080:80
        volumes:
            - ./src/public:/var/www/public
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
            - ./docker/StocklistLogs/nginx:/var/log/nginx/
        depends_on:
            - php
  
    php:
        build: ./docker/php
        user: ${user}
        container_name: Stocklist-php-fpm
        volumes:
            - ./src:/var/www
            - ./docker/StocklistLogs/php:/var/log/php/
        links:
            - db
        depends_on:
            - db
    
    db:
        build: ./docker/mysql
        container_name: Stocklist-db
        ports:
            - 3360:3306
        environment:
            MYSQL_DATABASE: Stocklist-database
            MYSQL_USER: Stocklist-user
            MYSQL_PASSWORD: Stocklist-password
            MYSQL_ROOT_PASSWORD: Stocklist-root
            TZ: Asia/Tokyo

    node:
        build: ./docker/node
        container_name: Stocklist-node
        volumes:
            - ./client:/mnt/client/
        stdin_open: true
        tty: true
        command: [sh, -c, npm install && npm run serve -- --port 8080] 