version: '3'

services:

    nginx:    
        image: nginx:1.17-alpine
        container_name: "Stocklist-nginx"
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/StocklistLogs/nginx:/var/log/nginx/
        depends_on:
            - php
  
    php:
        build: ./docker/php
        user: ${user}
        container_name: "Stocklist-php-fpm"
        volumes:
            - ./src:/var/www
            - ./docker/StocklistLogs/php:/var/log/php/
        links:
            - db
        depends_on:
            - db
    
    db:
        build: ./docker/mysql
        container_name: "Stocklist-db"
        volumes:
            - ./docker/mysql/conf.d:/etc/mysql/conf.d
            - ./docker/StocklistLogs/mysql:/var/log/mysql/
        ports:
            - 3360:3306
        environment:
            MYSQL_DATABASE: Stocklist-database
            MYSQL_USER: Stocklist-user
            MYSQL_PASSWORD: Stocklist-password
            MYSQL_ROOT_PASSWORD: Stocklist-root
            TZ: "Asia/Tokyo"
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
